groups:
  - name: spark_alerts
    rules:
      - alert: SparkExecutorFailure
        expr: spark_executor_count < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Spark executor failure detected"