scrape_configs:
  - job_name: 'spark-master'
    static_configs:
      - targets: ['172.20.0.2:8080']
    metrics_path: /metrics/prometheus
    scrape_interval: 5s

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['172.20.0.3:8081', '172.20.0.10:8081', '172.20.0.11:8081']
    metrics_path: /metrics/prometheus
    scrape_interval: 5s

  - job_name: 'spark-applications'
    static_configs:
      - targets: ['172.20.0.2:4040']
    metrics_path: /metrics/prometheus
    scrape_interval: 5s
